# Run test and then create release with goreleaser
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19.1
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Get dependencies
        run: |
          go mod download
      - name: Test
        run: go test -v cmd/injector/*.go

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.19.1
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}